stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collecton.test_size
    outs:
    - data/raw
  data_preparation:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed

  model_training:
    cmd: python src/model_train.py
    deps:
    - data/processed
    - src/model_train.py
    outs:
    - model.pkl
  model-evaluation:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - matrics.json
